name: CICD Pipeline for deploying AWS Resources
run-name: ${{ github.actor }} has triggered the workflow

on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./pre

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./pre

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./pre

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./pre

  deploy-arch:
    name: Deploy Architecture
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  delayed-destroy:
    name: Destroy Resources
    runs-on: ubuntu-latest
    needs: deploy-arch
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Delayed Destroy
        uses: jakejarvis/wait-action@master
        with:
          time: '20m'

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
